### ISSUE TITLE
Implement generic functions?

### ISSUE THREAD

**Issue by jwhitfieldseed** [jwhitfieldseed/prequel#66]
Right now supported functions are [hard-wired in the grammar](https://github.com/jwhitfieldseed/prequel/blob/master/src/sql.pegjs#L152). 

The grammar contains aggregate functions only. That should change so that #44 can be treated as a "simple" (non-aggregate) function.

:question: Should hard-wired functions be replaced with a generic `function_expr` and runtime lookup by function name? 
:question: Which other [simple functions](https://www.sqlite.org/lang_corefunc.html) should we support? 

Generic functions have some advantages:

* Simpler grammar, smaller parser
* No grammar changes for new functions
* We could expose an API like `registerFunction(name, fn)` for user-defined functions

Some things to consider with runtime lookup:

* Check the function exists
* Check the function is called in the right context (e.g. no aggregates in `WHERE`)
* Check the arity is correct :grey_question: 
* Check that `DISTINCT` is applied legally [(aggregate functions with exactly 1 argument)](https://www.sqlite.org/lang_aggfunc.html)
* Allow `*` parameter for `COUNT` only.

**Comment by jwhitfieldseed** [comment]
@SteveFortune I'm interested in your thoughts :thought_balloon:

**Comment by SteveFortune** [comment]
I like the idea of registering functions for runtime lookup. Perhaps we could pass some sort of specification object to `registerFunction`, like this:

```Javascript
registerFunction({
  name: ...,
  arity: 3, // Optional; omitting expects variadic args
  verify: (ctx) => ... // Optional function that receives some sort of 'context' object and validates that the usage is correct. Not sure what the ctx might be
  fn: (a, b, c) => ... // The actual fn
});
```

Exposing that to the user as an extension point also sounds useful. E.g. if I want to call some obscure, non-standard function to achieve a domain-specific task. (See SQL Server's [CREATE FUNCTION](https://msdn.microsoft.com/en-GB/library/ms186755.aspx)).

I have some qualms about pushing everything, even the core aggregate functions, out of the grammar, as they seem heavily embedded in the SQL language syntax. Shouldn't it be the parser's job to verify syntactical correctness, not our runtime? 

It might make sense to keep the core function expressions in the grammar to enforce consistency and register non-aggregate functions at runtime, although then there is the risk that it becomes laborious to maintain 2 separate methods of evaluating functions.

**Comment by jwhitfieldseed** [comment]
#65 adds runtime lookup.
